root: "https://polklusbedrijf.nl"
name: Pol klusbedrijf
description: ""

metas:
  title: =title
  description: =description
  icon: /img/icon.png
  lang: nl
  generator: true

analytics:
  umami_id: "2aa0f2b1-518b-4961-a179-111a2c73757e"
