name: Polklusbedrijf

kvk: 69661448
phone: 06 130 377 65
email: info@polklusbedrijf.nl
address:
  street: Händelstraat 17
  zipcode: 5144 GV
  city: Waalwijk

year: 2024

company:
  logo: /img/pkb-logo.svg
  name: Pol klusbedrijf

socials:
  - name: facebook
    icon: logo-facebook
    url: "https://www.facebook.com/people/Pol-Klusbedrijf/100054346236199/"
  - name: instagram
    icon: logo-instagram
    url: "https://www.instagram.com/pol_klusbedrijf/"
