name: Deploy website to cPanel

on:
  push:
    branches:
      - main # voer deployment uit bij een wijzing in main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Haal de repository op
        uses: actions/checkout@v3

      - name: 🛠️ Installeer Deno en Lume
        run: |
          curl -fsSL https://deno.land/install.sh | sh
          export DENO_INSTALL="$HOME/.deno"
          export PATH="$DENO_INSTALL/bin:$PATH"
          deno task build

      - name: 🚀 Deploy naar cPanel via rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          CPANEL_USER: ${{ secrets.CPANEL_USER }}
          CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
          CPANEL_POORT: "4000"
          DEPLOY_PATH: "/home/${{ secrets.CPANEL_USER }}/public_html/"

        run: |
          # Configureer SSH key
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_deploy_key
          chmod 600 ~/.ssh/github_deploy_key
          ssh-keyscan -p $CPANEL_POORT -H $CPANEL_HOST >> ~/.ssh/known_hosts
        
          # Test verbinding met SSH, expliciet de juiste sleutel gebruiken
          ssh -i ~/.ssh/github_deploy_key -p $CPANEL_POORT $CPANEL_USER@$CPANEL_HOST "echo ✅ Verbonden!"
        
          # Synchroniseer bestanden met rsync, met expliciete sleutel
          rsync -avz -e "ssh -i ~/.ssh/github_deploy_key -p $CPANEL_POORT" --delete _site/ $CPANEL_USER@$CPANEL_HOST:$DEPLOY_PATH
        
          echo "✅ Deployment voltooid!"

